import Link from "next/link";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { PUBLIC_HOUSE_STYLES } from "@/lib/server/house-styles";

export default function HomePage() {
  return <div id="top"><div className="paper-noise" aria-hidden="true"/><div className="page-shell"><SiteHeader/><main id="main-content">
    <section className="phase2-hero creative-hero" aria-labelledby="hero-title">
      <div className="creative-hero-copy"><p className="hero-eyebrow"><span/> Your photo, redrawn with character</p><h1 id="hero-title">Turn a favourite photo into <em>expressive, handcrafted artwork.</em></h1><p>Choose a loose hand-drawn finish or a bold geometric collage, add an optional personal touch, and create up to three artwork versions.</p><Link className="button button-primary hero-cta" href="/private-test">Enter the private test <span aria-hidden="true">→</span></Link><div className="private-status"><span aria-hidden="true"/><div><b>Private testing underway</b><small>Invite-only generation. Public purchasing is not available.</small></div></div></div>
      <div className="hero-composition" aria-hidden="true"><span className="hero-paper hero-paper-coral"/><span className="hero-paper hero-paper-blue"/><span className="hero-paper hero-paper-ochre"/><span className="hero-loop"/><span className="hero-scribble"/><span className="hero-star">✦</span><span className="hero-dot hero-dot-one"/><span className="hero-dot hero-dot-two"/></div>
    </section>
    <section className="house-styles" aria-labelledby="styles-title"><div className="section-intro editorial-intro"><span className="section-kicker">Two TurnPhotoArt house styles</span><h2 id="styles-title">Two distinct ways to make the moment yours.</h2><p>Both preserve the subject and source colours while changing the drawing language, texture and rhythm.</p></div><div className="style-public-grid">{PUBLIC_HOUSE_STYLES.map((style,index)=><article key={style.id} className={`public-style-card style-${index+1}`}><div className={`style-abstract style-abstract-${index+1}`} aria-hidden="true"><i/><i/><i/><i/><i/></div><div className="style-card-copy"><span>House style 0{index+1}</span><h3>{style.name}</h3><p>{style.description}</p></div></article>)}</div></section>
    <section className="creative-process" aria-labelledby="process-title"><div><p className="section-kicker">Simple by design</p><h2 id="process-title">From favourite photo to finished artwork.</h2><p>One calm flow, with no editing tools or complicated controls.</p></div><ol><li><b>01</b><span><strong>Upload</strong><small>Choose one JPEG, PNG or WebP photo.</small></span></li><li><b>02</b><span><strong>Art direct</strong><small>Pick a house style and optional personality.</small></span></li><li><b>03</b><span><strong>Create & download</strong><small>Keep any of your three finished versions.</small></span></li></ol></section>
    <section className="trust-panel" aria-labelledby="trust-title"><div className="trust-mark" aria-hidden="true">T</div><div><p className="section-kicker">A considered private test</p><h2 id="trust-title">Your work stays focused on the artwork.</h2><p>Reference and result image bytes are not stored in the database. Private-test images are never published automatically, and refreshing the studio may remove browser-held results.</p></div><Link href="/privacy">Read the privacy details <span aria-hidden="true">→</span></Link></section>
    <section className="private-cta" aria-labelledby="private-cta-title"><div aria-hidden="true" className="cta-cut-paper"><i/><i/><i/></div><div><p className="section-kicker light">Invite-only creative studio</p><h2 id="private-cta-title">Ready to see your photo differently?</h2><p>The private test includes up to three downloadable artwork versions. No payment is collected.</p></div><Link className="button button-primary" href="/private-test">Enter the private test <span aria-hidden="true">→</span></Link></section>
  </main><SiteFooter/></div></div>;
}
