"use client";
/* eslint-disable @next/next/no-img-element -- Reference and result images are temporary browser-local blob URLs. */

import { ChangeEvent, useEffect, useRef, useState } from "react";
import { Download, Plus, Trash2, Upload } from "lucide-react";
import Link from "next/link";
import { validateImageFile } from "@/lib/browser/image-validation";
import { PUBLIC_HOUSE_STYLES, type HouseStyleId } from "@/lib/server/house-styles";

type ArtworkResult={url:string;version:number;styleId:HouseStyleId;personality:string|null;setNumber:number};

export function PrivateStudio(){
  const inputRef=useRef<HTMLInputElement>(null); const fileRef=useRef<File|null>(null); const resultsRef=useRef<ArtworkResult[]>([]);
  const [file,setFile]=useState<File|null>(null); const [referenceUrl,setReferenceUrl]=useState<string|null>(null); const [setToken,setSetToken]=useState<string|null>(null); const [style,setStyle]=useState<HouseStyleId>("bold-playful"); const [personality,setPersonality]=useState(""); const [results,setResults]=useState<ArtworkResult[]>([]); const [successfulCount,setSuccessfulCount]=useState(0); const [busy,setBusy]=useState(false); const [status,setStatus]=useState(""); const [error,setError]=useState(""); const [setNumber,setSetNumber]=useState(1);
  useEffect(()=>{fileRef.current=file},[file]); useEffect(()=>{resultsRef.current=results},[results]);
  useEffect(()=>()=>{if(referenceUrl)URL.revokeObjectURL(referenceUrl);resultsRef.current.forEach((r)=>URL.revokeObjectURL(r.url))},[referenceUrl]);
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(busy){event.preventDefault();event.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[busy]);
  const choose=async(chosen:File)=>{if(setToken)return;setError("");try{await validateImageFile(chosen);if(referenceUrl)URL.revokeObjectURL(referenceUrl);setFile(chosen);setReferenceUrl(URL.createObjectURL(chosen));}catch(reason){setError(reason instanceof Error?reason.message:"Choose a valid JPEG, PNG or WebP image.")}};
  const onFile=(event:ChangeEvent<HTMLInputElement>)=>{const chosen=event.target.files?.[0];event.target.value="";if(chosen)void choose(chosen)};
  const createSet=async()=>{if(!file)return null;setStatus("Preparing your reference photo…");const form=new FormData();form.append("reference",file);const response=await fetch("/api/artwork-sets",{method:"POST",body:form});const body=await response.json();if(!response.ok)throw new Error(body.error||"The artwork could not be prepared.");setSetToken(body.artworkSetToken);setSuccessfulCount(body.successfulCount);return String(body.artworkSetToken)};
  const generate=async(token=setToken)=>{if(!file||!token||successfulCount>=3)return;setStatus(`Applying the ${PUBLIC_HOUSE_STYLES.find((s)=>s.id===style)?.name} style…`);const idempotency=crypto.randomUUID();const form=new FormData();form.append("reference",file);form.append("style",style);if(personality.trim())form.append("personality",personality);const response=await fetch("/api/artwork-sets/generate",{method:"POST",headers:{"x-artwork-set-token":token,"x-idempotency-key":idempotency},body:form});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||"The artwork could not be created.");}setStatus("Adding the finishing details…");const blob=await response.blob();if(blob.type!=="image/png")throw new Error("The artwork response could not be read.");const version=Number(response.headers.get("x-artwork-version")||successfulCount+1);const count=Number(response.headers.get("x-successful-count")||successfulCount+1);const result={url:URL.createObjectURL(blob),version,styleId:style,personality:personality.trim()?personality.trim():null,setNumber};setResults((current)=>[...current,result]);setSuccessfulCount(count);setStatus("Your artwork is ready to download.")};
  const createArtwork=async()=>{if(!file||busy||successfulCount>=3)return;setBusy(true);setError("");try{const token=setToken||await createSet();await generate(token);}catch(reason){setError(reason instanceof Error?reason.message:"The artwork could not be created.");setStatus("");}finally{setBusy(false)}};
  const clearReference=()=>{if(setToken)return;if(referenceUrl)URL.revokeObjectURL(referenceUrl);setReferenceUrl(null);setFile(null);setError("")};
  const newSet=()=>{if(referenceUrl)URL.revokeObjectURL(referenceUrl);setFile(null);setReferenceUrl(null);setSetToken(null);setSuccessfulCount(0);setPersonality("");setStatus("Choose a new reference photo when you’re ready.");setError("");setSetNumber((current)=>current+1)};
  const download=(result:ArtworkResult)=>{const link=document.createElement("a");link.href=result.url;link.download=`turnphotoart-${result.styleId}-${result.setNumber}-${result.version}.png`;link.click()};
  const count=[...personality].length; const currentResults=results.filter((result)=>result.setNumber===setNumber); const previousResults=results.filter((result)=>result.setNumber!==setNumber); const hasSuccess=successfulCount>0; const canTryAnother=hasSuccess&&successfulCount<3;
  return <div className="private-studio-shell"><header className="private-studio-header"><Link className="wordmark" href="/"><span aria-hidden="true" className="wordmark-mark">T</span>TurnPhotoArt</Link><span className="private-pill">Private test</span></header><main id="main-content" className="private-studio-main" aria-busy={busy}><div className="private-title"><p className="section-kicker">Controlled generation test</p><h1>Create your artwork.</h1><p>Your set includes up to three artwork versions. Download any version you love.</p></div>
  <section className="private-workspace" aria-label="Artwork creation controls"><div className="reference-panel"><h2>1. Reference photo</h2><input ref={inputRef} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={onFile}/>{referenceUrl?<><div className="reference-image"><img src={referenceUrl} alt="Selected reference photo"/></div>{!setToken?<div className="reference-actions"><button type="button" onClick={()=>inputRef.current?.click()}>Replace</button><button type="button" onClick={clearReference}><Trash2 size={16}/>Remove</button></div>:<p className="reference-note">This photo will be used for each version in this set.</p>}</>:<button className="private-drop" type="button" onClick={()=>inputRef.current?.click()}><Upload aria-hidden="true"/><b>Choose a reference photo</b><span>JPEG, PNG or WebP · up to 10 MB</span></button>}</div>
  <div className="direction-panel"><h2>2. Choose a house style</h2><div className="private-style-grid">{PUBLIC_HOUSE_STYLES.map((item)=><label key={item.id} className={style===item.id?"selected":""}><input type="radio" name="style" value={item.id} checked={style===item.id} onChange={()=>setStyle(item.id)}/><b>{item.name}</b><span>{item.description}</span></label>)}</div><label className="personality-field" htmlFor="personality"><b>Add more personality</b><span>Add colours, decorations, mood or background details. We’ll keep the original subject recognisable.</span><textarea id="personality" value={personality} onChange={(e)=>setPersonality(e.target.value)} maxLength={160} placeholder="Yellow flowers, a tiny party hat, and little blue stars…"/><small>{count} / 160</small></label>
  {!hasSuccess?<button className="button button-primary private-generate" type="button" disabled={!file||busy} onClick={createArtwork}>Create my artwork</button>:null}{canTryAnother?<div className="optional-version"><p>Not quite what you imagined?</p><button className="button button-secondary private-generate" type="button" disabled={busy} onClick={createArtwork}><Plus size={18}/>Try another version</button></div>:null} {status?<p className="operation-status" role="status" aria-live="polite">{status}</p>:null}{error?<p className="private-error" role="alert">{error}</p>:null}</div></section>
  <section className="generation-gallery" aria-labelledby="gallery-title"><div><p className="section-kicker">Artwork versions</p><h2 id="gallery-title">{successfulCount} of 3 artwork versions created</h2></div>{currentResults.length?<div className="result-grid">{currentResults.map((result)=><article key={`${result.setNumber}-${result.version}`}><img src={result.url} alt={`Artwork version ${result.version}`}/><div><span>Version {result.version}</span><h3>{PUBLIC_HOUSE_STYLES.find((s)=>s.id===result.styleId)?.name}</h3>{result.personality?<p>{result.personality.slice(0,60)}{result.personality.length>60?"…":""}</p>:null}<button className="button button-primary" type="button" onClick={()=>download(result)}><Download size={17}/>Download artwork</button></div></article>)}</div>:<div className="gallery-empty">Completed artwork versions will stay here until this tab is refreshed or closed.</div>}{successfulCount>=3?<button className="button button-secondary new-set" type="button" onClick={newSet}>Create artwork from a new photo</button>:null}{previousResults.length?<div className="previous-results"><h3>Earlier completed artwork</h3><div className="result-grid">{previousResults.map((result)=><article key={`${result.setNumber}-${result.version}`}><img src={result.url} alt={`Earlier artwork version ${result.version}`}/><div><span>Version {result.version}</span><h3>{PUBLIC_HOUSE_STYLES.find((s)=>s.id===result.styleId)?.name}</h3><button className="button button-secondary" type="button" onClick={()=>download(result)}><Download size={17}/>Download artwork</button></div></article>)}</div></div>:null}</section>
  </main></div>;
}
