"use client";
/* eslint-disable @next/next/no-img-element -- Reference and result images are temporary browser-local blob URLs. */

import { ChangeEvent, useEffect, useRef, useState } from "react";
import { Download, Plus, Trash2, Upload } from "lucide-react";
import Link from "next/link";
import { validateImageFile } from "@/lib/browser/image-validation";
import { PUBLIC_HOUSE_STYLES, type HouseStyleId } from "@/lib/server/house-styles";

type ArtworkResult={url:string;version:number;styleId:HouseStyleId;personality:string|null};

function friendlyError(reason: unknown, fallback: string) {
  if (!(reason instanceof Error)) return fallback;
  if (/provider response is uncertain|reservation needs review|generation_state_unknown/i.test(reason.message)) return "We’re checking whether your artwork finished successfully. Please wait before trying again.";
  if (/failed to fetch|unexpected token|json|networkerror/i.test(reason.message)) return "We couldn’t reach the studio. Check your connection and try again.";
  return reason.message || fallback;
}

export function PrivateStudio(){
  const inputRef=useRef<HTMLInputElement>(null); const resultsRef=useRef<ArtworkResult[]>([]);
  const [file,setFile]=useState<File|null>(null); const [referenceUrl,setReferenceUrl]=useState<string|null>(null); const [setToken,setSetToken]=useState<string|null>(null); const [style,setStyle]=useState<HouseStyleId>("bold-playful"); const [personality,setPersonality]=useState(""); const [results,setResults]=useState<ArtworkResult[]>([]); const [successfulCount,setSuccessfulCount]=useState(0); const [busy,setBusy]=useState(false); const [status,setStatus]=useState(""); const [error,setError]=useState("");
  useEffect(()=>{resultsRef.current=results},[results]);
  useEffect(()=>()=>{if(referenceUrl)URL.revokeObjectURL(referenceUrl);resultsRef.current.forEach((r)=>URL.revokeObjectURL(r.url))},[referenceUrl]);
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(busy){event.preventDefault();event.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[busy]);
  const choose=async(chosen:File)=>{if(setToken)return;setError("");try{await validateImageFile(chosen);if(referenceUrl)URL.revokeObjectURL(referenceUrl);setFile(chosen);setReferenceUrl(URL.createObjectURL(chosen));}catch(reason){setError(friendlyError(reason,"Choose a valid JPEG, PNG or WebP image."))}};
  const onFile=(event:ChangeEvent<HTMLInputElement>)=>{const chosen=event.target.files?.[0];event.target.value="";if(chosen)void choose(chosen)};
  const createSet=async()=>{if(!file)return null;setStatus("Preparing your photo…");const form=new FormData();form.append("reference",file);const response=await fetch("/api/artwork-sets",{method:"POST",body:form});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"This image could not be uploaded. Choose a smaller JPEG, PNG or WebP file and try again.");setSetToken(body.artworkSetToken);setSuccessfulCount(body.successfulCount);return String(body.artworkSetToken)};
  const generate=async(token=setToken)=>{if(!file||!token||successfulCount>=3)return;setStatus("Creating your illustration…");const idempotency=crypto.randomUUID();const form=new FormData();form.append("reference",file);form.append("style",style);if(personality.trim())form.append("personality",personality);const response=await fetch("/api/artwork-sets/generate",{method:"POST",headers:{"x-artwork-set-token":token,"x-idempotency-key":idempotency},body:form});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||"The artwork could not be created. Please try again.");}setStatus("Adding the finishing details…");const blob=await response.blob();if(blob.type!=="image/png")throw new Error("The artwork response could not be read. Please try again.");const version=Number(response.headers.get("x-artwork-version")||successfulCount+1);const count=Number(response.headers.get("x-successful-count")||successfulCount+1);const result={url:URL.createObjectURL(blob),version,styleId:style,personality:personality.trim()?personality.trim():null};setResults((current)=>[...current,result]);setSuccessfulCount(count);setStatus("Your artwork is ready.")};
  const createArtwork=async()=>{if(!file||busy||successfulCount>=3)return;setBusy(true);setError("");try{const token=setToken||await createSet();await generate(token)}catch(reason){setError(friendlyError(reason,"The artwork could not be created. Please try again."));setStatus("")}finally{setBusy(false)}};
  const clearReference=()=>{if(setToken)return;if(referenceUrl)URL.revokeObjectURL(referenceUrl);setReferenceUrl(null);setFile(null);setError("")};
  const download=(result:ArtworkResult)=>{const link=document.createElement("a");link.href=result.url;link.download=`turnphotoart-${result.styleId}-version-${result.version}.png`;link.click()};
  const count=[...personality].length; const hasSuccess=successfulCount>0; const canTryAnother=hasSuccess&&successfulCount<3; const isComplete=successfulCount>=3;
  return <div className="private-studio-shell"><div className="paper-noise" aria-hidden="true"/><header className="private-studio-header"><Link className="wordmark" href="/"><span aria-hidden="true" className="wordmark-mark">T</span>TurnPhotoArt</Link><span className="private-pill">Private creative studio</span></header><main id="main-content" className="private-studio-main" aria-busy={busy}><div className="private-title"><p className="section-kicker">One photo · two house styles · three versions</p><h1>Create something with <em>character.</em></h1><p>Choose a reference, art-direct the feeling, then let TurnPhotoArt redraw the moment.</p></div>
  <section className="private-workspace" aria-label="Artwork creation controls"><div className="reference-panel creative-surface"><div className="panel-heading"><span>01</span><h2>Choose a reference photo</h2></div><input ref={inputRef} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={onFile}/>{referenceUrl?<><div className="reference-image"><img src={referenceUrl} alt="Selected reference photo"/></div>{!setToken?<div className="reference-actions"><button type="button" onClick={()=>inputRef.current?.click()}>Replace photo</button><button type="button" onClick={clearReference}><Trash2 size={16}/>Remove</button></div>:<p className="reference-note">This reference is locked for every version in this set.</p>}</>:<button className="private-drop" type="button" onClick={()=>inputRef.current?.click()}><span className="upload-mark" aria-hidden="true"><Upload/></span><b>Choose your photo</b><span>JPEG, PNG or WebP · up to 10 MB</span><small>Portrait, landscape and square images are welcome.</small></button>}</div>
  <div className="direction-panel creative-surface"><div className="panel-heading"><span>02</span><h2>Choose a house style</h2></div><div className="private-style-grid">{PUBLIC_HOUSE_STYLES.map((item,index)=><label key={item.id} className={style===item.id?"selected":""}><input type="radio" name="style" value={item.id} checked={style===item.id} onChange={()=>setStyle(item.id)}/><span className="style-radio-status">{style===item.id?"Selected":"Select style"}</span><span className={`studio-style-motif studio-style-motif-${index+1}`} aria-hidden="true"><i/><i/><i/><i/></span><b>{item.name}</b><span className="style-description">{item.description}</span></label>)}</div><label className="personality-field" htmlFor="personality"><b><span>03</span> Add more personality <em>Optional</em></b><span id="personality-help">Add colours, decorations, mood or background details. The original subject stays recognisable.</span><textarea id="personality" value={personality} onChange={(e)=>setPersonality(e.target.value)} maxLength={160} aria-describedby="personality-help personality-count" placeholder="Yellow flowers, a tiny party hat, and little blue stars…"/><small id="personality-count">{count} / 160</small></label>
  <div className="creation-action"><span>04 · Create artwork</span>{!hasSuccess?<button className="button button-primary private-generate" type="button" disabled={!file||busy} onClick={createArtwork}>Create my artwork</button>:null}{canTryAnother?<div className="optional-version"><p>Not quite what you imagined?</p><button className="button button-secondary private-generate" type="button" disabled={busy} onClick={createArtwork}><Plus size={18}/>Try another version</button></div>:null}</div>{status?<p className="operation-status" role="status" aria-live="polite">{status}</p>:null}{error?<p className="private-error" role="alert">{error}</p>:null}</div></section>
  <section className="generation-gallery" aria-labelledby="gallery-title"><div className="gallery-heading"><p className="section-kicker">Artwork versions</p>{isComplete?<div className="completion-state"><b>3 of 3 artwork versions created</b><h2 id="gallery-title">Private test complete</h2><p>You’ve created all three artwork versions included in this private test. Download any version you’d like to keep.</p></div>:<><h2 id="gallery-title">Your finished artwork lives here.</h2><p>{successfulCount} of 3 artwork versions created</p></>}</div>{results.length?<div className="result-grid">{results.map((result)=><article key={result.version}><img src={result.url} alt={`Artwork version ${result.version}`}/><div><span>Version {result.version}</span><h3>{PUBLIC_HOUSE_STYLES.find((s)=>s.id===result.styleId)?.name}</h3>{result.personality?<p>{result.personality.slice(0,60)}{result.personality.length>60?"…":""}</p>:<p className="no-personality">House style only</p>}<button className="button button-primary" type="button" onClick={()=>download(result)}><Download size={17}/>Download artwork</button></div></article>)}</div>:<div className="gallery-empty"><span aria-hidden="true">✦</span><b>Your canvas is waiting.</b><p>Completed artwork versions will stay here until this tab is refreshed or closed.</p></div>}</section>
  </main></div>;
}
