"use client";
/* eslint-disable @next/next/no-img-element -- Reference and result images are temporary browser-local blob URLs. */

import { ChangeEvent, useEffect, useRef, useState } from "react";
import { Download, LockKeyhole, Plus, Trash2, Upload } from "lucide-react";
import Link from "next/link";
import { validateImageFile } from "@/lib/browser/image-validation";
import { PUBLIC_HOUSE_STYLES, type HouseStyleId } from "@/lib/server/house-styles";

type ArtworkResult={url:string;version:number;styleId:HouseStyleId;personality:string|null};

export function PrivateStudio(){
  const inputRef=useRef<HTMLInputElement>(null); const fileRef=useRef<File|null>(null); const resultsRef=useRef<ArtworkResult[]>([]);
  const [file,setFile]=useState<File|null>(null); const [referenceUrl,setReferenceUrl]=useState<string|null>(null); const [setToken,setSetToken]=useState<string|null>(null); const [style,setStyle]=useState<HouseStyleId>("bold-playful"); const [personality,setPersonality]=useState(""); const [results,setResults]=useState<ArtworkResult[]>([]); const [successfulCount,setSuccessfulCount]=useState(0); const [busy,setBusy]=useState(false); const [status,setStatus]=useState(""); const [error,setError]=useState("");
  useEffect(()=>{fileRef.current=file},[file]); useEffect(()=>{resultsRef.current=results},[results]);
  useEffect(()=>()=>{if(referenceUrl)URL.revokeObjectURL(referenceUrl);resultsRef.current.forEach((r)=>URL.revokeObjectURL(r.url))},[referenceUrl]);
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(busy){event.preventDefault();event.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[busy]);
  const choose=async(chosen:File)=>{if(setToken)return;setError("");try{await validateImageFile(chosen);if(referenceUrl)URL.revokeObjectURL(referenceUrl);setFile(chosen);setReferenceUrl(URL.createObjectURL(chosen));}catch(reason){setError(reason instanceof Error?reason.message:"Choose a valid JPEG, PNG or WebP image.")}};
  const onFile=(event:ChangeEvent<HTMLInputElement>)=>{const chosen=event.target.files?.[0];event.target.value="";if(chosen)void choose(chosen)};
  const createSet=async()=>{if(!file||busy)return;setBusy(true);setError("");setStatus("Preparing your reference photo…");try{const form=new FormData();form.append("reference",file);const response=await fetch("/api/artwork-sets",{method:"POST",body:form});const body=await response.json();if(!response.ok)throw new Error(body.error||"The artwork set could not be created.");setSetToken(body.artworkSetToken);setSuccessfulCount(body.successfulCount);setStatus("Reference photo locked to this artwork set.");}catch(reason){setError(reason instanceof Error?reason.message:"The artwork set could not be created.");setStatus("");}finally{setBusy(false)}};
  const generate=async()=>{if(!file||!setToken||busy||successfulCount>=3)return;setBusy(true);setError("");setStatus(`Applying the ${PUBLIC_HOUSE_STYLES.find((s)=>s.id===style)?.name} style…`);const idempotency=crypto.randomUUID();try{const form=new FormData();form.append("reference",file);form.append("style",style);if(personality.trim())form.append("personality",personality);const response=await fetch("/api/artwork-sets/generate",{method:"POST",headers:{"x-artwork-set-token":setToken,"x-idempotency-key":idempotency},body:form});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||"The artwork could not be created.");}setStatus("Adding the finishing details…");const blob=await response.blob();if(blob.type!=="image/png")throw new Error("The artwork response could not be read.");const version=Number(response.headers.get("x-artwork-version")||successfulCount+1);const count=Number(response.headers.get("x-successful-count")||successfulCount+1);const result={url:URL.createObjectURL(blob),version,styleId:style,personality:personality.trim()?personality.trim():null};setResults((current)=>[...current,result]);setSuccessfulCount(count);setStatus("Your artwork is ready.");}catch(reason){setError(reason instanceof Error?reason.message:"The artwork could not be created.");setStatus("");}finally{setBusy(false)}};
  const clearReference=()=>{if(setToken)return;if(referenceUrl)URL.revokeObjectURL(referenceUrl);setReferenceUrl(null);setFile(null);setError("")};
  const newSet=()=>{if(!window.confirm("Start a new artwork set? This unlocks the photo picker for another reference. Download every result you want to keep first."))return;if(referenceUrl)URL.revokeObjectURL(referenceUrl);results.forEach((r)=>URL.revokeObjectURL(r.url));setFile(null);setReferenceUrl(null);setSetToken(null);setResults([]);setSuccessfulCount(0);setPersonality("");setStatus("");setError("")};
  const download=(result:ArtworkResult)=>{const link=document.createElement("a");link.href=result.url;link.download=`turnphotoart-${result.styleId}-${result.version}.png`;link.click()};
  const count=[...personality].length;
  return <div className="private-studio-shell"><header className="private-studio-header"><Link className="wordmark" href="/"><span aria-hidden="true" className="wordmark-mark">T</span>TurnPhotoArt</Link><span className="private-pill">Private test</span></header><main id="main-content" className="private-studio-main" aria-busy={busy}><div className="private-title"><p className="section-kicker">Controlled generation test</p><h1>Create three artwork versions.</h1><p>One reference photo is locked to each set. Download every successful version before refreshing or leaving this tab.</p></div>
  <section className="private-workspace" aria-label="Artwork set controls"><div className="reference-panel"><h2>1. Reference photo</h2><input ref={inputRef} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={onFile}/>{referenceUrl?<><div className="locked-image"><img src={referenceUrl} alt="Selected reference photo"/>{setToken?<span><LockKeyhole size={15}/> Locked to this set</span>:null}</div>{!setToken?<div className="reference-actions"><button type="button" onClick={()=>inputRef.current?.click()}>Replace</button><button type="button" onClick={clearReference}><Trash2 size={16}/>Remove</button></div>:<p className="lock-note">A different photo requires a new artwork set.</p>}</>:<button className="private-drop" type="button" onClick={()=>inputRef.current?.click()}><Upload aria-hidden="true"/><b>Choose a reference photo</b><span>JPEG, PNG or WebP · up to 10 MB</span></button>}</div>
  <div className="direction-panel"><h2>2. Choose a house style</h2><div className="private-style-grid">{PUBLIC_HOUSE_STYLES.map((item)=><label key={item.id} className={style===item.id?"selected":""}><input type="radio" name="style" value={item.id} checked={style===item.id} onChange={()=>setStyle(item.id)}/><b>{item.name}</b><span>{item.description}</span></label>)}</div><label className="personality-field" htmlFor="personality"><b>Add more personality</b><span>Add colours, decorations, mood or background details. We’ll keep the original subject recognisable.</span><textarea id="personality" value={personality} onChange={(e)=>setPersonality(e.target.value)} maxLength={160} placeholder="Yellow flowers, a tiny party hat, and little blue stars…"/><small>{count} / 160</small></label>
  {!setToken?<button className="button button-primary private-generate" type="button" disabled={!file||busy} onClick={createSet}><LockKeyhole size={18}/>Lock photo and start artwork set</button>:<button className="button button-primary private-generate" type="button" disabled={busy||successfulCount>=3} onClick={generate}><Plus size={18}/>{successfulCount>=3?"Three versions created":"Create artwork version"}</button>} {status?<p className="operation-status" role="status" aria-live="polite">{status}</p>:null}{error?<p className="private-error" role="alert">{error}</p>:null}</div></section>
  <section className="generation-gallery" aria-labelledby="gallery-title"><div><p className="section-kicker">Three artwork versions included</p><h2 id="gallery-title">{successfulCount} of 3 artwork versions created</h2></div>{results.length?<div className="result-grid">{results.map((result)=><article key={result.version}><img src={result.url} alt={`Artwork version ${result.version}`}/><div><span>Version {result.version}</span><h3>{PUBLIC_HOUSE_STYLES.find((s)=>s.id===result.styleId)?.name}</h3>{result.personality?<p>{result.personality.slice(0,60)}{result.personality.length>60?"…":""}</p>:null}<button className="button button-secondary" type="button" onClick={()=>download(result)}><Download size={17}/>Download</button></div></article>)}</div>:<div className="gallery-empty">Completed artwork versions will stay here until this tab is refreshed or closed.</div>}{setToken?<button className="button button-secondary new-set" type="button" onClick={newSet}>Start a new artwork set</button>:null}</section>
  </main></div>;
}
